events {}

http {
    # Basic Security Headers
    server_tokens off; # Hide Nginx version
    add_header X-Frame-Options "SAMEORIGIN";
    add_header X-XSS-Protection "1; mode=block";

    server {
        listen 80;
        server_name your_public_ip;

        location / {
            proxy_pass http://haunted-house:5000;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            
            # Security: Limit request size for Three.js assets
            client_max_body_size 20M;
        }
    }
}